import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QuantumExplainer } from "@/components/QuantumExplainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* 全站共用 footer */}
        <footer className="mt-12 border-t border-gray-200 bg-gray-50">
          <div className="mx-auto max-w-5xl px-6 py-8">
            <QuantumExplainer
              compact
              className="bg-gray-50 border-none shadow-none px-0 py-0"
            />
          </div>
        </footer>
      </body>
    </html>
  );
}
